spring:
  application:
    name: webflux-task-manager-app
  data:
    mongodb:
      uri: mongodb://localhost:27017/webfluxTaskManager

token:
  secret: 1HE9W02H4BFDMZMAA&AWPQ03746678385BSMWSSOPWLSVDGGKDFMSBZXTEROTJHNSOWMSDWGHVDCNSDC&DC

external:
  fakestore:
    base-url: https://fakestoreapi.com
